#!/bin/bash

cd /app

inotifywait -r -m ./apps  -e modify,create -e moved_to |
    while read path action file; do
        if [[ $file =~ \.ex$ || \.exs$ ]]; then
                echo "('$action') The file '$path/$file' will be formatted"
                mix format $path/$file
        fi
    done
